language: python
sudo: required

env:
  - FLASK=0.11
  - FLASK=0.12
  - FLASK=1.0
  - FLASK=1.1

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install coveralls

install:
  - pip install flask==$FLASK
  - pip install .

script:
  - coverage run --source flask_gopher setup.py test

after_success:
  - coveralls
